
#alias python='python3.6'
#alias python='$HOME/softwares/conda/bin/python3'
#alias pip='pip-3.6'

alias ll='ls -l'
alias sq='~/bin/sq.sh'
alias sqls='source ~/bin/sqls.sh'
alias sqcd='source ~/bin/sqcd.sh'
alias sqr='source ~/bin/sqr.sh'
alias ficd='source ~/bin/ficd.sh'
alias grepr='grep "reached required" OUTCAR; grep "energy without" OUTCAR|tail -1; less OSZICAR|tail -1'
alias grepe='~/bin/grepe.sh'
alias rma='~/bin/rma.sh'
alias ifreachedreq='source ~/bin/ifreachedreq.sh'


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
#__conda_setup="$('/global/homes/c/changzhi/softwares/conda/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
#if [ $? -eq 0 ]; then
    #eval "$__conda_setup"
#else
    #if [ -f "/global/homes/c/changzhi/softwares/conda/etc/profile.d/conda.sh" ]; then
        #. "/global/homes/c/changzhi/softwares/conda/etc/profile.d/conda.sh"
    #else
        #export PATH="/global/homes/c/changzhi/softwares/conda/bin:$PATH"
    #fi
#fi
#unset __conda_setup
# <<< conda initialize <<<
#conda deactivate
#
export PATH="/global/homes/c/changzhi/softwares/conda/bin:$PATH"

#export PATH=~/softwares/vasp/bin:$PATH
#export PYTHONPATH=~/softwares/vasp:$PYTHONPATH
