# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# SLAC S3DF - source all files under ~/.profile.d
if [[ -e ~/.profile.d && -n "$(ls -A ~/.profile.d/)" ]]; then
  source <(cat $(find -L  ~/.profile.d -name '*.conf' | sort))
fi

# User specific aliases and functions

#alias sq='~/bin/sq.sh'
#alias sqls='source ~/bin/sqls.sh'
alias sqcd='source ~/bin/slurm/sqcd'
#alias sqr='source ~/bin/sqr.sh'
alias ficd='source ~/bin/slurm/ficd'
#alias grepr='grep "reached required" OUTCAR; grep "energy without" OUTCAR|tail -1; less OSZICAR|tail -1'
#alias grepe='~/bin/grepe.sh'
#alias rma='~/bin/rma.sh'
#alias ifreachedreq='source ~/bin/ifreachedreq.sh'
PATH=~/bin/slurm:$PATH

alias python='python3.8'
alias pip='pip-3.8'

# export PATH=$PATH:$HOME/bin/python

alias conda='/sdf/home/c/changzhi/softwares/anoconda3/bin/conda'

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
#__conda_setup="$('/sdf/home/c/changzhi/softwares/anoconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
#if [ $? -eq 0 ]; then
    #eval "$__conda_setup"
#else
    #if [ -f "/sdf/home/c/changzhi/softwares/anoconda3/etc/profile.d/conda.sh" ]; then
        #. "/sdf/home/c/changzhi/softwares/anoconda3/etc/profile.d/conda.sh"
    #else
        #export PATH="/sdf/home/c/changzhi/softwares/anoconda3/bin:$PATH"
    #fi
#fi
#unset __conda_setup
# <<< conda initialize <<<


module use $HOME/softwares/modules

export EASYBUILD_MODULES_TOOL=Lmod
export EASYBUILD_PREFIX=$SCRATCH/softwares/easybuild
module use $EASYBUILD_PREFIX/modules/all
module load EasyBuild
complete -o default -C "/usr/bin/python3.8 /sdf/home/c/changzhi/.local/lib/python3.8/site-packages/myqueue/complete.py" mq


export C_INCLUDE_PATH=/sdf/home/c/changzhi/softwares/libxc/install/include:$C_INCLUDE_PATH
export LIBRARY_PATH=/sdf/home/c/changzhi/softwares/libxc/install/lib:$LIBRARY_PATH
export LD_LIBRARY_PATH=/sdf/home/c/changzhi/softwares/libxc/install/lib:$LD_LIBRARY_PATH

